Migrate to Next.js and support RainbowKit
darwinia-network/darwinia-staking-ui pull request #47
Opened 2023-08-07 01:10 UTC by JayJay1024

2023-08-07 03:32 UTC, fewensa requested changes

2023-08-07 03:32 UTC, fewensa commented on .github/workflows/deploy-dev.yml
> +          node-version: '16.16'
```suggestion
          node_version: '16.16'
```

2023-08-07 03:32 UTC, fewensa commented on .github/workflows/deploy-prd.yml
> +          node-version: '16.16'
```suggestion
          node_version: '16.16'
```

2023-08-07 03:32 UTC, fewensa commented on .github/workflows/deploy-stg.yml
> +          node-version: '16.16'
```suggestion
          node_version: '16.16'
```

2023-08-07 03:45 UTC, fewensa approved these changes

2023-08-10 01:56 UTC, 1022ranji approved these changes

2023-08-10 02:03 UTC, merged